#!/usr/bin/env node
var fs = require('fs'),
	syncExec = require('sync-exec'),
	userid = require('userid');

	var user, group;
	var host_uid = process.env.HOST_UID
	var host_gid = process.env.HOST_GID
	var target_user =  process.env.DOCKER_USERNAME
	var target_group = process.env.DOCKER_GROUPNAME

	console.log("Looking if user already exists for UID", host_uid)


	// Check if our host uid and gid are already assigned to another group
	try {
		user = userid.username(host_uid);

		if (user == undefined || user === "undefined" )
			user = userid.groupname(host_gid);

	} catch (e) {
		console.log("No User with id", host_uid)
	} finally {
		console.log("Found user", user)
	}

	try {
		group = userid.groupname(host_gid);

		if (group == undefined || group === "undefined" )
			group = userid.groupname(host_uid);

	} catch (e) {
		console.log("No group with id", host_gid)
	} finally {
		console.log("Found group", group)
	}



	if (group != target_group) {
		if (group != undefined && group != "undefined")
			console.log(syncExec("groupmod -g 1333337 " + group).stdout)

		console.log(syncExec("groupmod -g " + host_gid + " " + target_group).stdout); 
	}

	if (user != target_user) {
		if (user != undefined && user != "undefined")
			console.log(syncExec("usermod -u 1333338 " + user).stdout)

		console.log(syncExec("usermod -u " + host_uid + " " + target_user).stdout); 
	}

