#!/usr/bin/env bash
set -e

echo "Setting permissions for db container..."
/tools/permission_fix 
chown -R odoo:odoo /var/lib/odoo /mnt/extra-addons
echo "Done."

su -s /bin/bash -c '/entrypoint.sh openerp-server' odoo

#echo '* Starting Command'
#echo $COMMAND

#$COMMAND

#debug
#tail -f /dev/null