#!/usr/bin/env bash
set -e

echo "Setting permissions for db container..."
/tools/permission_fix
chown -R postgres:postgres /var/lib/postgresql /dump
echo "Done."

/docker-entrypoint.sh postgres

#echo '* Starting Command'
#echo $COMMAND

#$COMMAND

#echo "Done."

#tail -f /dev/null


