#!/usr/bin/env bash
hostname=`hostname`

##########################################
## OpenERP Backup
## Backup databases: openerpdb1, openerpdb2
##########################################


# Dump DBs
for db in secrets
do
  filename="/dump/*${db}*.sql.tar"
  
  if [ -f $filename ]; then
    createdb -U odoo $db
    pg_restore -F t -c -U odoo -d $db $filename
  fi
done

exit 0