installer:
  build: docker-images/installer
  environment:
    DOMAIN: ${DOMAIN}
    BACKUP_DOMAIN: ${BACKUP_DOMAIN}
    ROOT: /var/www/html
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
    ACTION: ${ACTION}
  entrypoint: "/tools/action.sh"
  volumes_from:
    - nginx
  volumes:
    - "./docker-images/installer/bin:/tools"
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"


nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
    - ./permissions.sh:/permissions.sh

  environment:
    FOLDER: "/var/www/html"
    USER: nginx
    ENTRYPOINT: nginx
    VIRTUAL_HOST: quinn.magento
    MYSQL_ROOT_PASSWORD: pw
  command: "/permissions.sh"

  volumes_from:
    - php


ftp:
  image: stilliard/pure-ftpd
  command: "/usr/sbin/pure-ftpd -c 30 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R"
  ports:
    - "30000-30009:30000-30009"
    - "2121:21"
  volumes_from:
    - php


php:
  build: docker-images/php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "solr:solr"
    - "mysql:mysql"
  volumes:
    - .:/var/www/html


mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
    FOLDER: "/var/lib/mysql"
    USER: mysql
    ENTRYPOINT: "/entrypoint.sh mysqld --user=mysql --console"
  command: "/permissions.sh"
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    - ./permissions.sh:/permissions.sh


solr:
  build: docker-images/solr
cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest